default: &default
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  adapter: postgresql
  username:  <%= ENV.fetch("DATABASE_USERNAME") { } %>
  password:  <%= ENV.fetch("DATABASE_PASSWORD") { } %>
development:
  <<: *default
  database: tracktune_api_development

test:
  <<: *default
  database: tracktune_api_test

production:
  <<: *default
  database: tracktune_api_production
